### ISSUE TITLE
Possible query endpoint inconsistency

### ISSUE THREAD

**Issue by DRK3** [decentralized-identity/confidential-storage#110]
Hi,

In the [Searching Encrypted Documents section](https://identity.foundation/secure-data-store/#searching-encrypted-documents), it lists two ways to search through encrypted documents:

1. [Using a specifically indexed value](https://identity.foundation/secure-data-store/#example-32-data-vault-query-for-a-specifically-indexed-value)
2. [Using the has keyword](https://identity.foundation/secure-data-store/#example-34-data-vault-query-for-a-particular-attribute-name)

In the examples, the endpoint for option 1 is listed as `https://example.com/encrypted-data-vaults/{vaultID}`, while the endpoint for option 2 is `https://example.com/encrypted-data-vaults/{vaultID}/queries`.

Are the endpoints being different intentional? The "queries" text in option 2 seems to suggest that it would be for all queries, but it also makes sense to me that the first path would be fine for all querying.

Thanks!

**Comment by dlongley** [comment]
Both endpoints should be the same, specifically: `https://example.com/encrypted-data-vaults/{vaultId}/query`

**Comment by DRK3** [comment]
OK, thanks @dlongley :)
