### ISSUE TITLE
[OFFLINE] What is the expected behavior for an agent talking to an EDV Server Instance that is offline (or otherwise not available)?

### ISSUE THREAD

**Issue by mwherman2000** [decentralized-identity/confidential-storage#206]
Perhaps somewhat out of scope for the actual Spec but ...

What is the expected behavior for an agent talking to an EDV Server Instance that is offline (or otherwise unavailable)?

Is the usual behavior for the agent to queue the messages it wants to send to the EDV Server Instance until the Instance comes back online?

This is for the Decentralized Twitter app scenario.

**Comment by tplooker** [comment]
@mwherman2000 I would assume the client would receive "connection denied", the chairs and editors have labeled this pending close pre-migration to the new repos, please comment if you feel differently.

**Comment by mwherman2000** [comment]
I would assume the different REST calls defined in the specification would return specific HTTP error nodes ...these should be documented in the spec with great precision, n'est pas?
