### ISSUE TITLE
Alphabet proposal for layers

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/confidential-storage#74]
https://github.com/decentralized-identity/secure-data-store/issues/35#issuecomment-640895873

Layer A - Byte Storage CRUD (IPFS / MongoDB / Whatever...)
Layer B - Logical Storage CRUD (Vault, Document, Index)
Layer C - Logical Permissions CRUD (ZCaps / OAuth / TXAuth)... can `<role>.<action>.<resource>`... however you want to enforce that.
Layer D - Message Based CRDTs (firebase style, gun.js, etc...)
Layer E - Standards Based Data Structures (app manifest / webrtc rendevouz / didcomm connection preferences / aries connections / xbox user profile / bing ad preferences)

**Comment by agropper** [comment]
Please clarify:
- Policy is decided at Layer C? 
- Access is enforced at Layer B or maybe A and B?
- How are replay attacks mitigated?

**Comment by OR13** [comment]
@agropper 

Permissions = Policy + Enforcement => Layer C

Replay attacks are against a permissions system, they are mitigated at layer C as well.

You can see that TxAuth is at Layer C. 

Its my understanding the TxAuth can be used to defend any resource server, so it makes sense to think of Layer B as a resource server, and Layer C as the permissions / authorization layer.

... it may be the case that some implementors want to use ZCaps or vanilla OAuth to defend their resource server... under this layering scheme, they could replace TxAuth with ZCaps or vice versa (ZCaps are used in the current edv implementation).

**Comment by agropper** [comment]
@OR13 If both Policy + Enforcement => Layer C, can Layers B and C be operated by different entities?

**Comment by OR13** [comment]
@agropper yes, thats the case with vanilla OAuth and resource servers today.

I might use Okta for my authorization server, and I might run my own resource server that only supports CRUD on resources when the proper okta signed `access_token` is provided.

However its worth pointing out... the resource server trusts the permissions layer... in the case of OAuth, by validating `access_tokens`, in the case of ZCaps today, by validating ZCaps (no need for a 3rd party authorization server).

**Comment by agropper** [comment]
@OR13 In that case, with vanilla OAuth and resource servers, we have a huge privacy problem because the resource server gets to see Alice's policies as well as who is asking for access. This lack of separation of concerns seems to be counter to the decentralization rubrics. 

Which, I think brings us back to @jmandel's question in #73

**Comment by OR13** [comment]
@agropper no, the resource server gets to see the `access_token` which is configured by the policy on the authorization server. The same thing is true of `TxAuth`, afaik... 

See https://developer.okta.com/docs/guides/validate-access-tokens/go/overview/#access-tokens-vs-id-tokens

https://oauth.xyz/tokens/

The resource server can only see what is in the token... in the case of OAuth.xyz... thats something like this:

```
{
    "token1": [
        {
            "actions": [
                "read",
                "write",
                "dolphin"
            ],
            "locations": [
                "https://server.example.net/",
                "https://resource.local/other"
            ],
            "datatypes": [
                "metadata",
                "images"
            ]
        }
    ],
    "token2": [
        {
            "actions": [
                "foo",
                "bar",
                "dolphin"
            ],
            "locations": [
                "https://resource.other/"
            ],
            "datatypes": [
                "data",
                "pictures"
            ]
        }
    ]
}
```

**Comment by agropper** [comment]
I don't know about okta but with TxAuth, the requesting party goes to an authorization server with a resource access request and gets a token it can bring to the resource server. The token is different than the authorization request. The authorization request, for instance, might include a reason and requesting party credentials. Neither of those needs to be shared with the resource server.

**Comment by OR13** [comment]
@agropper its the same, the AS yields a token, and the token is consumed by the resource server. TxAuth has much better rules about how to get the token, but at the end of the day, the token (and all data contained in it) will be consumed by the resource server.

**Comment by jonnycrunch** [comment]
I would prefer layer A as Block storage, as in systems like MongoDB and/or IPFS there is a concept of block storage of raw bytes, but there is a logical layer either over this or intrinsic to this that has logic about how it is chunked and/or the format of the data and metadata about the block.

**Comment by Vir-Cotto** [comment]
There is an open question about whether or not level A should be abstracted to the application layer, or whether or not that should be an implementation detail.

**Comment by jonnycrunch** [comment]
The concept of Sharding is see as more of the how the data is chunked and stored, and it would be important to decide if this lives in Layer A of B.

**Comment by msporny** [comment]
> Logical Permissions

May want to rename this "Authorization" -- because that's more or less what the layer is about... we may want to change it to XYZ Authorization where XYZ is something more descriptive about Layer B.

**Comment by agropper** [comment]
Which layers have policies (and notification options, for example) as opposed to permissions?

**Comment by msporny** [comment]
> Layer D - Message Based CRDTs

We may want to just call this layer: Replication -- because CRDTs and Messaged-Based are not the only ways to do replication.

**Comment by csuwildcat** [comment]
> We may want to just call this layer: Replication -- because CRDTs and Messaged-Based are not the only ways to do replication.

It's fine to codify a Strategies approach in the spec that allows for multiple replication options, but the spec should define a standard CRDT option and how the appropriate layer must be implemented to correctly replicate in accordance with it.

**Comment by agropper** [comment]
Layer E is sort-of out of scope. Even so, we might use Published instead of Standards-based in order to promote decentralization rubrics one way or another.

**Comment by EvanTedesco** [comment]
Replication layer or reconciliation layer given that not all data is necessarily "replicated" across instances?

**Comment by csuwildcat** [comment]
> Layer E is sort-of out of scope. Even so, we might use Published instead of Standards-based in order to promote decentralization rubrics one way or another.

I was talking about Layer D (in reference to the Layers as noted in this proposal), not Layer E. I absolutely believe this spec MUST specify a replication Strategies section, and that it should codify at least one standard CRDT Strategy. With this, the project cannot reliably be used to create a universal personal/application datastore that can be implemented in a ubiquitous, inferentially interoperable way.

**Comment by agropper** [comment]
@csuwildcat I know you were talking about Layer D. My comment accidentally collided with yours when I was posting it at the request of the chairs.

There's a lot of insistence from various folks that this or that requirement is a MUST without any particular link to a real-world use-case or business model. Many, maybe all, of these MUST requirements have privacy implications to the data subject, the enterprises, and the requesting parties. Please bear with me as I try to envision use-cases every time someone says this or that is a MUST requirement without citing a use-case or acknowledging the privacy impact. I'm not trying to argue with your intent. I'm just hoping to stay engaged and educated and avoid jumping to conclusions.

**Comment by kdenhartog** [comment]
In an effort to try and consolidate the threads, here's two proposals that came from #44 which is nearly the same as this topic.

From myself,
> Layer 1: Storage layer
Layer 2: Replication layer
Layer 3: Integrity layer

From @csuwildcat

>Layer 1: Message Layer - required encryption, replication, and routing bits that must be integrated into messages
Layer 2: Storage Layer - messages are stored, managed, and permissioned as a coherent singular mass
Layer 3: Query Layer - how the storage layer groups, indexes, and exposes the data in the storage layer

In general, I'm liking the direction were heading better than what I originally proposed, but I'm still undecided as to the "horse I'm backing". I'll keep following the thread to see what emerges.

**Comment by emacsen** [comment]
Based on the interest in Datashards being the lowest abstraction for this standard, we would prefer that it be named as such in the specification.

**Comment by OR13** [comment]
@OR13 to consider spec text to clarify layers, for lower 2 layers.

**Comment by OR13** [comment]
Closing my own issue
